# Admin data models
"""
Admin data models for the Shadow Puppet Interactive System.
Contains Pydantic models for User, Character, Storyline, and Settings.
"""
from .user import User, UserCreate, UserResponse, LoginRequest, LoginResponse, TokenPayload, PasswordChangeRequest, AdminPasswordResetRequest
from .character import (
    CharacterDB,
    CharacterPartDB,
    SkeletonBindingDB,
    Character,
    CharacterPart,
    SkeletonBinding,
    CharacterCreate,
    CharacterUpdate,
    CharacterResponse,
    CharacterListResponse,
    PivotConfigUpdate,
    SkeletonBindingUpdate,
    CharacterPartUpload,
    REQUIRED_PARTS,
)
from .storyline import (
    StorylineDB,
    SegmentDB,
    Storyline,
    Segment,
    StorylineCreate,
    StorylineUpdate,
    StorylineResponse,
    StorylineListResponse,
    SegmentConfigUpdate,
    VideoUploadResponse,
    VALID_PATH_TYPES,
)
from .settings import (
    StorageSettings,
    QRCodeSettings,
    TimeoutSettings,
    RenderingSettings,
    CameraSettings,
    SystemSettings,
    StorageSettingsUpdate,
    QRCodeSettingsUpdate,
    TimeoutSettingsUpdate,
    RenderingSettingsUpdate,
    CameraSettingsUpdate,
    SystemSettingsUpdate,
    S3ConnectionTestRequest,
    S3ConnectionTestResponse,
    LANIPResponse,
    CameraDevice,
    CameraListResponse,
)

__all__ = [
    # User models
    "User",
    "UserCreate", 
    "UserResponse",
    "LoginRequest",
    "LoginResponse",
    "TokenPayload",
    "PasswordChangeRequest",
    "AdminPasswordResetRequest",
    # Character models
    "CharacterDB",
    "CharacterPartDB",
    "SkeletonBindingDB",
    "Character",
    "CharacterPart",
    "SkeletonBinding",
    "CharacterCreate",
    "CharacterUpdate",
    "CharacterResponse",
    "CharacterListResponse",
    "PivotConfigUpdate",
    "SkeletonBindingUpdate",
    "CharacterPartUpload",
    "REQUIRED_PARTS",
    # Storyline models
    "StorylineDB",
    "SegmentDB",
    "Storyline",
    "Segment",
    "StorylineCreate",
    "StorylineUpdate",
    "StorylineResponse",
    "StorylineListResponse",
    "SegmentConfigUpdate",
    "VideoUploadResponse",
    "VALID_PATH_TYPES",
    # Settings models
    "StorageSettings",
    "QRCodeSettings",
    "TimeoutSettings",
    "RenderingSettings",
    "CameraSettings",
    "SystemSettings",
    "StorageSettingsUpdate",
    "QRCodeSettingsUpdate",
    "TimeoutSettingsUpdate",
    "RenderingSettingsUpdate",
    "CameraSettingsUpdate",
    "SystemSettingsUpdate",
    "S3ConnectionTestRequest",
    "S3ConnectionTestResponse",
    "LANIPResponse",
    "CameraDevice",
    "CameraListResponse",
]
